(function(){'use strict';
const C=window.ChocoV2,N=window.ChocoNet,app=document.getElementById('app'),toastEl=document.getElementById('toast');
let host=null,client=null,facTimer=null,game=null,scene=null,lastMessageId=null,lastTeamId=null,observeTeamId=null;

function qs(k){return new URLSearchParams(location.search).get(k)}
function urlFor(role,extra={}){const u=new URL(location.href);u.search='';u.searchParams.set('role',role);Object.entries(extra).forEach(([k,v])=>v!=null&&u.searchParams.set(k,v));return u.toString()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(sec){sec=Math.max(0,Math.ceil(Number(sec)||0));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function phaseLabel(p){return({lobby:'Lobby',briefing:'Briefing',planning:'Planejamento',production:'Produção',results:'Resultados'})[p]||p}
function toast(msg,bad=false,ok=false){toastEl.textContent=msg;toastEl.className='toast'+(bad?' bad':ok?' ok':'');toastEl.hidden=false;clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.hidden=true,2800)}
function setPage(html){app.innerHTML=html;window.scrollTo(0,0)}
function stopEverything(){if(facTimer)clearInterval(facTimer);facTimer=null;if(client){client.stop();client=null}if(host){host.stop();host=null}if(game){game.destroy(true);game=null;scene=null}}
window.addEventListener('beforeunload',()=>{try{client?.stop()}catch{}});

function home(){stopEverything();setPage(`<main class="shell center"><section class="paper home-hero"><span class="eyebrow">CHOCOLATE COM PIMENTA · V2</span><h1>Fábrica<br>Cooperativa</h1><p class="paper-muted">Jogo top-down cooperativo para a dinâmica de alta performance. Cada equipe opera uma fábrica compartilhada em tempo real; o facilitador controla a sessão e as intervenções.</p><div class="row"><button class="btn primary" id="newSession">Criar sessão como facilitador</button><button class="btn light" id="joinSession">Entrar como participante</button></div><div class="warning" style="margin-top:18px;color:#5b4315;background:#fff0c6;border-color:#e2c16e"><b>Protótipo V2:</b> o navegador do facilitador atua como host da partida. Ele deve permanecer aberto durante a dinâmica.</div></section></main>`);document.getElementById('newSession').onclick=setupFacilitator;document.getElementById('joinSession').onclick=()=>joinPage(qs('code')||'')}

function setupFacilitator(){stopEverything();const last=N.lastSession(),saved=last&&N.loadSession(last);setPage(`<main class="shell center"><button class="btn ghost" id="back">← Início</button><section class="paper" style="margin-top:12px"><span class="eyebrow">FACILITADOR</span><h1 style="font-size:46px;letter-spacing:-.05em;margin:8px 0">Configurar dinâmica</h1><p class="paper-muted">A sessão será criada como um jogo multiplayer. Participantes entram pelo código, aguardam sua equipe e jogam na fábrica em tempo real.</p><label>Versão da dinâmica</label><div class="seg"><button class="on" data-mode="classic">Clássica</button><button data-mode="pressure">Panela de Pressão</button></div><div class="grid grid3"><div><label>Quantidade de equipes</label><input id="teamCount" type="number" min="2" max="4" value="2"></div><div><label>Planejamento (min)</label><input id="planning" type="number" min="1" value="10"></div><div><label>Produção (min)</label><input id="production" type="number" min="1" value="15"></div></div><button class="btn primary" id="createSession" style="width:100%;margin-top:18px">Criar sessão multiplayer</button>${saved?`<div style="margin-top:18px;border-top:1px solid #ead9cf;padding-top:16px"><p class="paper-muted small">Há uma sessão salva neste navegador: <b>${esc(last)}</b>.</p><button class="btn light" id="resumeSaved">Retomar sessão ${esc(last)}</button></div>`:''}</section></main>`);let mode='classic';document.getElementById('back').onclick=home;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('on',x===b))});document.getElementById('createSession').onclick=()=>startHost(C.createSession({mode,teamCount:document.getElementById('teamCount').value,planningMinutes:document.getElementById('planning').value,productionMinutes:document.getElementById('production').value}));if(saved)document.getElementById('resumeSaved').onclick=()=>startHost(saved)}

async function startHost(session){setPage(`<main class="shell center"><section class="panel connecting"><span class="eyebrow">ABRINDO SESSÃO</span><h1>Preparando a fábrica ${esc(session.code)}</h1><div class="spinner"></div><p class="muted">Conectando o host multiplayer…</p></section></main>`);host=new N.FacilitatorHost(session,ev=>{if(ev.type==='network-error')toast('Problema na conexão multiplayer.',true)});try{await host.start();renderFacilitatorShell();refreshFacilitator();facTimer=setInterval(refreshFacilitator,350)}catch(e){host?.stop();host=null;setPage(`<main class="shell center"><section class="paper"><span class="eyebrow">NÃO FOI POSSÍVEL ABRIR A SESSÃO</span><h1>${esc(e?.type==='unavailable-id'?'Este código já está em uso.':e.message||'Erro de conexão')}</h1><p class="paper-muted">Feche outra aba que possa estar hospedando a mesma sessão ou crie uma nova sessão.</p><button class="btn primary" id="retry">Voltar</button></section></main>`);document.getElementById('retry').onclick=setupFacilitator}}

function renderFacilitatorShell(){const s=host.session;setPage(`<main class="shell wide"><header class="header"><div><span class="eyebrow">FACILITADOR · ${s.mode==='pressure'?'PANELA DE PRESSÃO':'CLÁSSICA'}</span><h1>Chocolate com Pimenta V2</h1><p class="muted small">Host multiplayer ativo. Mantenha esta tela aberta durante a dinâmica.</p></div><div class="header-right"><span class="badge live">HOST ATIVO</span><div class="timer"><small id="phaseTag">${phaseLabel(s.phase).toUpperCase()}</small><b id="facClock">${fmt(C.phaseRemaining(s))}</b></div></div></header>
<section class="panel sessionbar"><div><div class="eyebrow">CÓDIGO</div><div class="code">${esc(s.code)}</div></div><div><div class="eyebrow">LINK DO PARTICIPANTE</div><div class="link" id="joinLink">${esc(urlFor('player',{code:s.code}))}</div></div><div class="row"><button class="btn sm" id="copyLink">Copiar link</button><button class="btn sm" id="openPlayer">Abrir jogador</button></div></section>
<section class="grid grid2" style="margin-top:14px"><article class="panel"><span class="eyebrow">CONTROLE DA APLICAÇÃO</span><h2>Fases e tempo</h2><div class="row"><button class="btn" id="startPlanning">Planejamento</button><button class="btn primary" id="startProduction">Produção</button><button class="btn" id="pauseBtn">Pausar</button><button class="btn" id="resumeBtn">Retomar</button><button class="btn" id="addMinute">+1 min</button><button class="btn danger" id="endSession">Encerrar</button></div><div class="row" style="margin-top:10px"><button class="btn sm" id="toggleEntries">${s.entriesOpen?'Fechar entradas':'Abrir entradas'}</button><button class="btn sm" id="autoAssign">Distribuir equipes automaticamente</button></div><div class="warning small" style="margin-top:12px">O facilitador é a autoridade da sessão: tempo, pausa, equipes, mensagens e intervenções são aplicados para todos em tempo real.</div></article><article class="panel"><span class="eyebrow">MENSAGEM AO JOGO</span><h2>Enviar orientação</h2><div class="message-box"><select id="messageTeam"><option value="">Todas as equipes</option>${s.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select><input id="messageText" maxlength="180" placeholder="Ex.: Revisem a divisão de trabalho."><button class="btn" id="sendMessage">Enviar pop-up</button></div><p class="muted tiny" style="margin-top:8px">A mensagem aparece sobre o jogo sem interromper a partida.</p></article></section>
${s.mode==='pressure'?`<section class="panel" style="margin-top:14px"><span class="eyebrow">PANELA DE PRESSÃO</span><h2>Intervenções do facilitador</h2><div class="grid grid3 interventions"><button class="btn" id="pressureTalent">Compartilhamento de talentos</button><button class="btn" id="pressureMarket">Mercado: Frutas Vermelhas 5 → 3</button><button class="btn" id="pressureFreezer">Freezer 3 → 2</button></div></section>`:''}
<section class="grid grid2" style="margin-top:14px"><article class="panel"><span class="eyebrow">GESTÃO DE PARTICIPANTES</span><div class="team-title"><h2>Lobby e equipes</h2><span class="pill" id="peopleCount">0 participantes</span></div><div id="participants" class="lobby-table"></div></article><article class="panel"><span class="eyebrow">EQUIPES</span><h2>Produção ao vivo</h2><div id="teamCards" class="grid"></div></article></section>
<section class="observe-grid" style="margin-top:14px"><article class="panel"><div class="team-title"><div><span class="eyebrow">OBSERVAÇÃO AO VIVO</span><h2 id="observeTitle">Selecione uma fábrica</h2></div><button class="btn sm" id="closeObserver">Fechar observador</button></div><div id="observerHolder"><div class="muted">Use “Observar” em uma das equipes para acompanhar o mapa sem interferir no jogo.</div></div></article><aside class="observer-side"><article class="panel"><span class="eyebrow">MÉTRICAS DA EQUIPE</span><div id="observerMetrics" class="muted small">Nenhuma equipe selecionada.</div></article><article class="panel"><span class="eyebrow">HISTÓRICO DA SESSÃO</span><div id="facLog" class="log"></div></article></aside></section>
<section class="panel" id="resultsPanel" style="margin-top:14px;display:none"><span class="eyebrow">RESULTADOS</span><div class="team-title"><h2>Fechamento da dinâmica</h2><button class="btn sm" id="exportResults">Baixar relatório JSON</button></div><div id="resultsBody"></div></section>
</main>`);
document.getElementById('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(urlFor('player',{code:s.code}));toast('Link copiado.',false,true)}catch{toast('Não foi possível copiar automaticamente.',true)}};document.getElementById('openPlayer').onclick=()=>window.open(urlFor('player',{code:s.code}),'_blank');document.getElementById('startPlanning').onclick=()=>host.setPhase('planning');document.getElementById('startProduction').onclick=()=>host.setPhase('production');document.getElementById('pauseBtn').onclick=()=>host.pause();document.getElementById('resumeBtn').onclick=()=>host.resume();document.getElementById('addMinute').onclick=()=>host.addMinute();document.getElementById('endSession').onclick=()=>{if(confirm('Encerrar a dinâmica agora?'))host.setPhase('results')};document.getElementById('toggleEntries').onclick=()=>{host.setEntries(!host.session.entriesOpen);document.getElementById('toggleEntries').textContent=host.session.entriesOpen?'Fechar entradas':'Abrir entradas'};document.getElementById('autoAssign').onclick=()=>host.autoAssign();document.getElementById('sendMessage').onclick=()=>{host.sendMessage(document.getElementById('messageText').value,document.getElementById('messageTeam').value||null);document.getElementById('messageText').value='';toast('Mensagem enviada.',false,true)};document.getElementById('messageText').onkeydown=e=>{if(e.key==='Enter')document.getElementById('sendMessage').click()};document.getElementById('closeObserver').onclick=()=>setObserver(null);
if(s.mode==='pressure'){document.getElementById('pressureTalent').onclick=()=>{try{host.shareTalent();toast('Compartilhamento de talentos aplicado.',false,true)}catch(e){toast(e.message,true)}};document.getElementById('pressureMarket').onclick=()=>host.applyMarket();document.getElementById('pressureFreezer').onclick=()=>host.applyFreezer()}
document.getElementById('participants').addEventListener('change',e=>{const sel=e.target.closest('[data-team-select]');if(sel)host.assignParticipant(sel.dataset.teamSelect,sel.value||null)});document.getElementById('participants').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b&&confirm('Remover este participante da sessão?'))host.removeParticipant(b.dataset.remove)});document.getElementById('teamCards').addEventListener('click',e=>{const b=e.target.closest('[data-observe]');if(b)setObserver(b.dataset.observe)});
}

function refreshFacilitator(){if(!host||!document.getElementById('facClock'))return;const s=host.session,parts=Object.values(s.participants).filter(p=>!p.removed);document.getElementById('facClock').textContent=fmt(C.phaseRemaining(s));document.getElementById('phaseTag').textContent=phaseLabel(s.phase).toUpperCase();document.getElementById('peopleCount').textContent=`${parts.length} participante${parts.length===1?'':'s'}`;document.getElementById('pauseBtn').disabled=s.pausedRemaining!=null||!s.endsAt;document.getElementById('resumeBtn').disabled=s.pausedRemaining==null;document.getElementById('toggleEntries').textContent=s.entriesOpen?'Fechar entradas':'Abrir entradas';
document.getElementById('participants').innerHTML=parts.length?parts.sort((a,b)=>a.joinedAt-b.joinedAt).map(p=>`<div class="participant-row"><div class="participant-name"><b>${esc(p.name)}</b><small><span class="dot ${p.connected?'online':''}"></span> ${p.connected?'conectado':'desconectado'} · ${p.teamId?esc(s.teams.find(t=>t.id===p.teamId)?.name):'<span class="pending">aguardando equipe</span>'}</small></div><select data-team-select="${p.id}"><option value="">Sem equipe</option>${s.teams.map(t=>`<option value="${t.id}" ${p.teamId===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select><button class="btn sm danger" data-remove="${p.id}">Remover</button></div>`).join(''):'<p class="muted small">Nenhum participante entrou ainda.</p>';
document.getElementById('teamCards').innerHTML=s.teams.map(t=>{const sc=C.scoreTeam(t,s),ps=parts.filter(p=>p.teamId===t.id);return`<div class="team-card panel" style="--team:${t.css}"><div class="team-title"><div><h3>${esc(t.name)}</h3><div class="people">${ps.map(p=>`<span class="person"><i class="dot ${p.connected?'online':''}"></i>${esc(p.name)}</span>`).join('')||'<span class="muted tiny">Sem participantes</span>'}</div></div><button class="btn sm" data-observe="${t.id}">Observar</button></div><div class="stat-grid" style="margin-top:10px"><div class="stat"><small>Pontos</small><b>${sc.total}</b></div><div class="stat"><small>Expedidos</small><b>${Object.values(t.delivered).reduce((a,b)=>a+b,0)}</b></div><div class="stat"><small>Tentativas</small><b>${t.attempts}/50</b></div><div class="stat"><small>Penalidades</small><b>${t.penalties.length}</b></div></div><div class="scoreline">${C.RECIPE_ORDER.map(k=>`<div class="scorechip"><small>${C.RECIPES[k].short}</small><b>${t.delivered[k]}</b></div>`).join('')}</div>${sc.standardsOk?'<div class="success tiny" style="margin-top:8px">Meta 10 + 10 + 10 atingida. Premium ativo.</div>':'<div class="warning tiny" style="margin-top:8px">Premium pendente até 10 + 10 + 10.</div>'}</div>`}).join('');
document.getElementById('facLog').innerHTML=[...s.events].reverse().slice(0,28).map(e=>`<div class="log-entry"><b>${new Date(e.t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</b> · ${esc(e.msg)}</div>`).join('')||'<div class="muted tiny">Sem eventos.</div>';
if(s.mode==='pressure'){document.getElementById('pressureTalent').disabled=s.interventions.talent;document.getElementById('pressureMarket').disabled=s.interventions.market;document.getElementById('pressureFreezer').disabled=s.interventions.freezer}
if(observeTeamId){const t=s.teams.find(t=>t.id===observeTeamId);if(t){const sc=C.scoreTeam(t,s);document.getElementById('observerMetrics').innerHTML=`<div class="stat-grid"><div class="stat"><small>Pontos</small><b>${sc.total}</b></div><div class="stat"><small>Premium pendente</small><b>${sc.pendingPremium}</b></div><div class="stat"><small>Erros freezer</small><b>${t.telemetry.freezerErrors}</b></div><div class="stat"><small>Retiradas cedo</small><b>${t.telemetry.earlyPulls}</b></div></div><div class="tiny muted" style="margin-top:10px">Pickups ${t.telemetry.pickups} · Drops ${t.telemetry.drops} · Lançamentos ${t.telemetry.throws} · Montagens ${t.telemetry.assemblyCompletions}</div>`}}
const resultsPanel=document.getElementById('resultsPanel');if(s.phase==='results'){resultsPanel.style.display='block';document.getElementById('resultsBody').innerHTML=s.teams.map(t=>{const sc=C.scoreTeam(t,s);return`<div class="result-team"><b>${esc(t.name)}</b><span><small class="muted">Pontos</small><br><b>${sc.total}</b></span><span><small class="muted">Expedidos</small><br><b>${Object.values(t.delivered).reduce((a,b)=>a+b,0)}</b></span><span><small class="muted">Tentativas</small><br><b>${t.attempts}</b></span><span><small class="muted">Penalidades</small><br><b>${t.penalties.length}</b></span><span><small class="muted">Premium</small><br><b>${sc.standardsOk?'ativo':'bloqueado'}</b></span></div>`}).join('');const exp=document.getElementById('exportResults');if(!exp._bound){exp._bound=true;exp.onclick=downloadResults}}else resultsPanel.style.display='none'}

function downloadResults(){const s=host.session,payload={exportedAt:new Date().toISOString(),session:{code:s.code,mode:s.mode,phase:s.phase,createdAt:s.createdAt},teams:s.teams.map(t=>({id:t.id,name:t.name,score:C.scoreTeam(t,s),inventory:t.inventory,attempts:t.attempts,delivered:t.delivered,penalties:t.penalties,telemetry:t.telemetry,events:t.events})),sessionEvents:s.events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`chocolate-com-pimenta-${s.code}-resultados.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

function setObserver(teamId){observeTeamId=teamId;const holder=document.getElementById('observerHolder'),title=document.getElementById('observeTitle');if(!holder)return;if(!teamId){holder.innerHTML='<div class="muted">Use “Observar” em uma das equipes para acompanhar o mapa sem interferir no jogo.</div>';title.textContent='Selecione uma fábrica';document.getElementById('observerMetrics').innerHTML='Nenhuma equipe selecionada.';return}const t=host.session.teams.find(t=>t.id===teamId);title.textContent=t?.name||'Fábrica';holder.innerHTML=`<iframe class="observer-frame" title="Observador da ${esc(t?.name||'equipe')}" src="${esc(urlFor('observer',{code:host.session.code,team:teamId,embed:'1'}))}"></iframe>`}

function joinPage(prefill=''){stopEverything();setPage(`<main class="shell center"><button class="btn ghost" id="back">← Início</button><section class="paper" style="margin-top:12px"><span class="eyebrow">PARTICIPANTE</span><h1 style="font-size:48px;letter-spacing:-.05em;margin:8px 0">Entrar na fábrica</h1><p class="paper-muted">Digite o código exibido pelo facilitador. Você será colocado no lobby e o facilitador definirá sua equipe.</p><label>Código da sessão</label><input id="joinCode" maxlength="6" autocomplete="off" value="${esc(prefill.toUpperCase())}" placeholder="ABC123"><label>Seu nome</label><input id="joinName" maxlength="40" autocomplete="name" placeholder="Nome para a dinâmica"><button class="btn primary" id="enterGame" style="width:100%;margin-top:18px">Entrar na sessão</button><div class="paper-muted tiny" style="margin-top:12px">Controles no jogo: WASD/setas para andar, E/Espaço para interagir, Shift para impulso e Q para lançar o objeto carregado.</div></section></main>`);document.getElementById('back').onclick=home;document.getElementById('joinCode').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);document.getElementById('enterGame').onclick=()=>connectPlayer(document.getElementById('joinCode').value,document.getElementById('joinName').value);document.getElementById('joinName').onkeydown=e=>{if(e.key==='Enter')document.getElementById('enterGame').click()}}

async function connectPlayer(code,name){code=String(code||'').trim().toUpperCase();name=String(name||'').trim();if(code.length!==6)return toast('Digite o código de 6 caracteres.',true);if(!name)return toast('Informe seu nome.',true);setPage(`<main class="shell center"><section class="panel connecting"><span class="eyebrow">ENTRANDO NA SESSÃO</span><h1>${esc(code)}</h1><div class="spinner"></div><p class="muted">Localizando o facilitador…</p></section></main>`);const oldToken=localStorage.getItem('choco-v2-token-'+code)||'';client=new N.ParticipantClient({code,name,token:oldToken||C.uid('token'),role:'player',onState:onClientState,onMessage:onClientMessage,onStatus:onClientStatus});try{await client.start();renderPlayerShell(name,code)}catch(e){client?.stop();client=null;setPage(`<main class="shell center"><section class="paper"><span class="eyebrow">NÃO FOI POSSÍVEL ENTRAR</span><h1>${esc(e.message||'Sessão indisponível')}</h1><p class="paper-muted">Confirme o código e verifique se o facilitador está com a sessão aberta.</p><button class="btn primary" id="tryAgain">Tentar novamente</button></section></main>`);document.getElementById('tryAgain').onclick=()=>joinPage(code)}}

function renderPlayerShell(name,code){setPage(`<main class="game-shell"><div class="game-top"><div class="game-identity"><small id="playerPhase">LOBBY</small><b id="playerIdentity">${esc(name)} · aguardando equipe</b></div><div class="hud-pills"><span class="pill" id="hudScore">0 pts</span><span class="pill" id="hudAttempts">0/50 tentativas</span><span class="pill" id="hudInventory">Barras 70</span></div><div class="timer"><small id="playerClockLabel">SESSÃO ${esc(code)}</small><b id="playerClock">00:00</b></div></div><section class="game-wrap"><div id="game"></div><div id="gameOverlay" class="overlay"><div class="overlay-card"><span class="eyebrow">LOBBY</span><h2>Aguardando o facilitador</h2><p class="paper-muted">Você entrou na sessão. O facilitador precisa atribuir você a uma equipe antes de liberar sua fábrica.</p></div></div><div class="game-help"><span><span class="kbd">WASD</span> / setas · mover</span><span><span class="kbd">E</span> / <span class="kbd">ESPAÇO</span> · pegar, soltar, usar estação</span><span><span class="kbd">SEGURE E</span> · montagem</span><span><span class="kbd">SHIFT</span> · impulso</span><span><span class="kbd">Q</span> · lançar</span></div></section></main>`)}

function onClientMessage(msg){if(msg.type==='kicked'){toast(msg.reason||'Você foi removido.',true);setTimeout(()=>joinPage(client?.code||''),800)}if(msg.type==='reject')toast(msg.reason||'Entrada recusada.',true)}
function onClientStatus(st){if(st.type==='connection-closed')toast('Conexão com o facilitador foi encerrada.',true)}
function onClientState(state,prev){if(!document.getElementById('gameOverlay')&&client?.role==='player')return;const s=state.session;if(client.role==='player'){const clock=document.getElementById('playerClock');if(clock)clock.textContent=fmt(s.pausedRemaining!=null?s.pausedRemaining:(s.endsAt?Math.max(0,(s.endsAt-Date.now())/1000):0));const phase=document.getElementById('playerPhase');if(phase)phase.textContent=phaseLabel(s.phase).toUpperCase();if(state.team){document.getElementById('playerIdentity').textContent=`${state.participant.name} · ${state.team.name}`;document.getElementById('hudScore').textContent=`${state.team.score.total} pts`;document.getElementById('hudAttempts').textContent=`${state.team.attempts}/50 tentativas`;document.getElementById('hudInventory').textContent=`Barras ${state.team.inventory.baseBars} · Fitas ${state.team.inventory.ribbons}`;ensureGame(false);scene?.applySnapshot(state);const overlay=document.getElementById('gameOverlay');if(s.pausedRemaining!=null){overlay.style.display='flex';overlay.innerHTML=`<div class="overlay-card"><span class="eyebrow">PAUSA DO FACILITADOR</span><h2>Dinâmica pausada</h2><p class="paper-muted">O jogo está congelado. Aguarde o facilitador retomar.</p></div>`}else if(s.phase==='lobby'||s.phase==='briefing'){overlay.style.display='flex';overlay.innerHTML=`<div class="overlay-card"><span class="eyebrow">${phaseLabel(s.phase).toUpperCase()}</span><h2>${state.team.name}</h2><p class="paper-muted">Você já está na sua fábrica. A produção ainda não começou.</p></div>`}else if(s.phase==='results'){overlay.style.display='flex';overlay.innerHTML=`<div class="overlay-card"><span class="eyebrow">ENCERRAMENTO</span><h2>${state.team.score.total} pontos</h2><p class="paper-muted">${resultText(state.team)}</p></div>`}else overlay.style.display='none';if(lastTeamId&&lastTeamId!==state.team.id)showGameNotice('REALOCADO',`Você agora está na ${state.team.name}. Adapte a estratégia e retome a produção.`);lastTeamId=state.team.id}else{document.getElementById('playerIdentity').textContent=`${state.participant.name} · aguardando equipe`;document.getElementById('hudScore').textContent='0 pts';document.getElementById('hudAttempts').textContent='0/50 tentativas';const overlay=document.getElementById('gameOverlay');overlay.style.display='flex';overlay.innerHTML='<div class="overlay-card"><span class="eyebrow">LOBBY</span><h2>Aguardando o facilitador</h2><p class="paper-muted">Você entrou na sessão. O facilitador precisa atribuir você a uma equipe.</p></div>'}
    const visibleMsgs=s.messages.filter(m=>!m.teamId||m.teamId===state.participant.teamId);const last=visibleMsgs[visibleMsgs.length-1];if(last&&last.id!==lastMessageId){lastMessageId=last.id;showGameNotice('MENSAGEM DO FACILITADOR',last.text)}}else{ensureGame(true);scene?.applySnapshot(state)}}
function resultText(team){const c=team.delivered,ok=team.score.standardsOk;return`Ao Leite ${c.milk} · Amargo ${c.dark} · Branco ${c.white} · Pistache ${c.pistachio} · Frutas Vermelhas ${c.berries} · Caramelo ${c.caramel}. ${ok?'Meta 10 + 10 + 10 atingida; pontuação premium contabilizada.':'Meta 10 + 10 + 10 não atingida; itens premium ficaram sem pontuar.'}`}
function showGameNotice(label,text){let box=document.getElementById('floatingNotice');if(!box){box=document.createElement('div');box.id='floatingNotice';box.style.cssText='position:fixed;left:50%;top:88px;transform:translateX(-50%);z-index:9998;max-width:620px;width:calc(100% - 28px);background:#fff8f1;color:#2c1813;border-radius:16px;padding:16px 18px;box-shadow:0 18px 70px rgba(0,0,0,.45);border:2px solid #d66c47';document.body.appendChild(box)}box.innerHTML=`<div class="eyebrow">${esc(label)}</div><div style="font-weight:900;font-size:20px;margin-top:4px">${esc(text)}</div>`;box.hidden=false;clearTimeout(box._t);box._t=setTimeout(()=>box.hidden=true,4200)}

async function observerPage(code,teamId){stopEverything();const embed=qs('embed')==='1';setPage(`<main class="${embed?'':'game-shell'}"><div class="game-top"><div class="game-identity"><small>OBSERVADOR</small><b>${esc(teamId||'Equipe')}</b></div><div class="hud-pills"><span class="pill" id="hudScore">0 pts</span><span class="pill" id="hudAttempts">0/50 tentativas</span><span class="pill" id="hudInventory">Barras 70</span></div><div class="timer"><small>SESSÃO ${esc(code)}</small><b id="playerClock">00:00</b></div></div><section class="game-wrap"><div id="game"></div><div id="gameOverlay" class="overlay"><div class="overlay-card"><span class="eyebrow">OBSERVADOR</span><h2>Conectando…</h2></div></div></section></main>`);client=new N.ParticipantClient({code,role:'observer',teamId,onState:(st)=>{document.getElementById('playerClock').textContent=fmt(st.session.pausedRemaining!=null?st.session.pausedRemaining:(st.session.endsAt?Math.max(0,(st.session.endsAt-Date.now())/1000):0));if(st.team){document.getElementById('hudScore').textContent=`${st.team.score.total} pts`;document.getElementById('hudAttempts').textContent=`${st.team.attempts}/50 tentativas`;document.getElementById('hudInventory').textContent=`Barras ${st.team.inventory.baseBars}`;ensureGame(true);scene?.applySnapshot(st);document.getElementById('gameOverlay').style.display='none'}},onStatus:()=>{}});try{await client.start()}catch(e){document.getElementById('gameOverlay').innerHTML=`<div class="overlay-card"><span class="eyebrow">OBSERVADOR</span><h2>Não foi possível conectar</h2><p class="paper-muted">${esc(e.message)}</p></div>`}}

function ensureGame(readOnly){if(game)return;scene=new FactoryScene(readOnly);game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#1b1411',width:1280,height:720,scene:[scene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false}})}

class FactoryScene extends Phaser.Scene{
  constructor(readOnly=false){super({key:'FactoryScene'});this.readOnly=readOnly;this.snapshot=null;this.playerNodes=new Map();this.itemNodes=new Map();this.stationGraphics=[];this.lastInputAt=0;this.lastInputKey='';this.lastSnapshotTeam=null}
  create(){this.cameras.main.setBackgroundColor('#1a1412');this.drawFloor();this.drawStations();this.createHud();if(!this.readOnly)this.setupControls()}
  drawFloor(){const g=this.add.graphics();g.fillStyle(0x211916,1);g.fillRect(0,0,1280,720);g.lineStyle(1,0x2c221e,.7);for(let x=24;x<1280;x+=48)g.lineBetween(x,22,x,698);for(let y=22;y<698;y+=48)g.lineBetween(22,y,1258,y);g.lineStyle(4,0x4b352d,1);g.strokeRect(22,22,1236,676);this.add.text(34,28,'CHOCOLATE COM PIMENTA · FÁBRICA',{fontFamily:'Arial',fontSize:'12px',fontStyle:'bold',color:'#bba79d'}).setDepth(20)}
  stationBox(s,fill,stroke=0x66473b,labelColor='#fff5ef'){const g=this.add.graphics();g.fillStyle(0x000000,.26);g.fillRoundedRect(s.x+6,s.y+7,s.w,s.h,10);g.fillStyle(fill,1);g.fillRoundedRect(s.x,s.y,s.w,s.h,10);g.lineStyle(3,stroke,1);g.strokeRoundedRect(s.x,s.y,s.w,s.h,10);this.add.text(s.x+s.w/2,s.y+s.h/2,s.label,{fontFamily:'Arial',fontSize:'11px',fontStyle:'bold',color:labelColor,align:'center',wordWrap:{width:s.w-12}}).setOrigin(.5).setDepth(5);return g}
  drawStations(){for(const s of C.MAP.rawBins){const r=C.RECIPES[s.recipe];this.stationBox(s,r.color,0x3b2821,r.id==='white'?'#2c1a14':'#fff');this.add.text(s.x+s.w/2,s.y+10,`${r.base} barra${r.base>1?'s':''}`,{fontFamily:'Arial',fontSize:'9px',color:r.id==='white'?'#5a493f':'#fff'}).setOrigin(.5,0).setDepth(6)}for(const s of C.MAP.wrappers){const wrapperRecipe=Object.values(C.RECIPES).find(r=>r.wrapper===s.wrapper);this.stationBox(s,wrapperRecipe?.wrapperColor||0x8d6c5c,0x3b2821,s.wrapper==='beige'?'#2c1a14':'#fff')}
    for(const s of C.MAP.assembly)this.stationBox(s,0x824a34,0xb86b4a);for(const s of C.MAP.counters)this.stationBox(s,0x65534a,0x8b7569);for(const s of C.MAP.finish){const col=s.resource==='ribbon'?0xb36048:s.resource==='tag'?0x5c7ca0:0x8f7ea6;this.stationBox(s,col,0x352822)}this.stationBox(C.MAP.freezer,0x315967,0x80c8d4);this.stationBox(C.MAP.freezerConsole,0x27414a,0x80c8d4);this.stationBox(C.MAP.dispatch,0x426a45,0x75b878);
    this.slotG=this.add.graphics().setDepth(7);this.progressG=this.add.graphics().setDepth(8);this.freezerStatus=this.add.text(C.MAP.freezer.x+C.MAP.freezer.w/2,C.MAP.freezer.y+248,'CARREGANDO',{fontFamily:'Arial',fontSize:'11px',fontStyle:'bold',color:'#c8edf3'}).setOrigin(.5).setDepth(10)}
  createHud(){this.hudG=this.add.graphics().setDepth(80);this.hudG.fillStyle(0x0d0a09,.91);this.hudG.fillRoundedRect(970,30,270,178,12);this.hudG.lineStyle(2,0x4c352d,1);this.hudG.strokeRoundedRect(970,30,270,178,12);this.add.text(990,45,'META DA FÁBRICA',{fontFamily:'Arial',fontSize:'11px',fontStyle:'bold',color:'#e58a68'}).setDepth(81);this.goalTexts={};C.RECIPE_ORDER.forEach((k,i)=>{this.goalTexts[k]=this.add.text(990,70+i*21,'',{fontFamily:'Arial',fontSize:'12px',fontStyle:i<3?'bold':'normal',color:i<3?'#fff':'#d7c6bd'}).setDepth(81)});this.scoreText=this.add.text(1155,45,'0 pts',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#fff'}).setDepth(81)}
  setupControls(){this.keys=this.input.keyboard.addKeys({up:'W',down:'S',left:'A',right:'D',up2:'UP',down2:'DOWN',left2:'LEFT',right2:'RIGHT',interact:'E',interact2:'SPACE',dash:'SHIFT',throw:'Q'});this.input.keyboard.on('keydown-E',()=>client?.action('interact'));this.input.keyboard.on('keydown-SPACE',()=>client?.action('interact'));this.input.keyboard.on('keydown-SHIFT',()=>client?.action('dash'));this.input.keyboard.on('keydown-Q',()=>client?.action('throw'))}
  applySnapshot(st){this.snapshot=st;const team=st.team;if(!team)return;if(this.lastSnapshotTeam&&this.lastSnapshotTeam!==team.id){this.clearDynamic()}this.lastSnapshotTeam=team.id}
  clearDynamic(){for(const n of this.playerNodes.values())n.destroy();for(const n of this.itemNodes.values())n.destroy();this.playerNodes.clear();this.itemNodes.clear()}
  update(time){if(this.snapshot?.team){this.renderTeam(this.snapshot.team,this.snapshot.session,time);if(!this.readOnly&&this.keys&&time-this.lastInputAt>50){this.lastInputAt=time;const input={up:this.keys.up.isDown||this.keys.up2.isDown,down:this.keys.down.isDown||this.keys.down2.isDown,left:this.keys.left.isDown||this.keys.left2.isDown,right:this.keys.right.isDown||this.keys.right2.isDown,interactHold:this.keys.interact.isDown||this.keys.interact2.isDown};const key=JSON.stringify(input);if(key!==this.lastInputKey||input.up||input.down||input.left||input.right||input.interactHold){this.lastInputKey=key;client?.sendInput(input)}}}}
  renderTeam(team,session,time){this.renderPlayers(team);this.renderItems(team);this.renderFreezer(team,session,time);this.renderProgress(team);const sc=team.score||{total:0,counts:team.delivered,standardsOk:false};this.scoreText.setText(`${sc.total} pts`);C.RECIPE_ORDER.forEach((k,i)=>{const r=C.RECIPES[k],n=team.delivered[k]||0;if(i<3)this.goalTexts[k].setText(`${r.short.padEnd(9,' ')} ${n}/10`);else this.goalTexts[k].setText(`${r.short.padEnd(9,' ')} ${n} · ${k==='berries'?session.berriesPoints:r.points} pts`);this.goalTexts[k].setColor(i<3&&n>=10?'#80d7a4':i<3?'#ffffff':'#d7c6bd')})}
  renderPlayers(team){const alive=new Set;for(const p of Object.values(team.players)){alive.add(p.id);let n=this.playerNodes.get(p.id);if(!n){n=this.makePlayerNode(p);this.playerNodes.set(p.id,n)}const lerp=this.snapshot.selfId===p.id?.38:.25;n.x=Phaser.Math.Linear(n.x,p.x,lerp);n.y=Phaser.Math.Linear(n.y,p.y,lerp);n.body.setFillStyle(team.color,1);n.initial.setText((p.name||'?').slice(0,1).toUpperCase());n.nameText.setText(p.name||'');n.status.setFillStyle(p.connected===false?0x777777:0x54c98a,1)}for(const[id,n]of this.playerNodes)if(!alive.has(id)){n.destroy();this.playerNodes.delete(id)}}
  makePlayerNode(p){const c=this.add.container(p.x,p.y).setDepth(50);const shadow=this.add.ellipse(0,14,42,18,0x000000,.25);const body=this.add.circle(0,0,18,0xffffff).setStrokeStyle(4,0x2d201b,1);const initial=this.add.text(0,-1,(p.name||'?')[0],{fontFamily:'Arial',fontSize:'14px',fontStyle:'bold',color:'#1d1411'}).setOrigin(.5);const nameText=this.add.text(0,27,p.name||'',{fontFamily:'Arial',fontSize:'10px',fontStyle:'bold',color:'#fff',backgroundColor:'#17110fcc',padding:{x:4,y:2}}).setOrigin(.5,0);const status=this.add.circle(14,-14,4,0x54c98a);c.add([shadow,body,initial,nameText,status]);c.body=body;c.initial=initial;c.nameText=nameText;c.status=status;return c}
  renderItems(team){const alive=new Set;for(const it of Object.values(team.items)){if(it.freezerSlot!=null)continue;alive.add(it.id);let n=this.itemNodes.get(it.id);if(!n){n=this.makeItemNode(it);this.itemNodes.set(it.id,n)}n.x=Phaser.Math.Linear(n.x,it.x,.35);n.y=Phaser.Math.Linear(n.y,it.y,.35);this.updateItemNode(n,it)}for(const[id,n]of this.itemNodes)if(!alive.has(id)){n.destroy();this.itemNodes.delete(id)}}
  makeItemNode(it){const r=C.RECIPES[it.recipeId],c=this.add.container(it.x,it.y).setDepth(45);const shadow=this.add.ellipse(3,7,35,15,0x000000,.3);const base=this.add.rectangle(0,0,34,22,r.color).setStrokeStyle(3,0x2f211c);const stripe=this.add.rectangle(0,0,34,5,r.wrapperColor).setVisible(false);const label=this.add.text(0,0,r.short.slice(0,3),{fontFamily:'Arial',fontSize:'8px',fontStyle:'bold',color:r.id==='white'?'#2c1813':'#fff'}).setOrigin(.5);const badge=this.add.text(20,-15,'',{fontFamily:'Arial',fontSize:'8px',fontStyle:'bold',color:'#fff',backgroundColor:'#9d392d',padding:{x:3,y:1}}).setOrigin(.5);c.add([shadow,base,stripe,label,badge]);c.base=base;c.stripe=stripe;c.badge=badge;return c}
  updateItemNode(n,it){const r=C.RECIPES[it.recipeId];n.base.setFillStyle(r.color);n.stripe.setVisible(!!it.wrapper);if(it.wrapper){const wr=Object.values(C.RECIPES).find(x=>x.wrapper===it.wrapper);n.stripe.setFillStyle(wr?.wrapperColor||0xffffff)}const comps=(it.ribbons?`F${it.ribbons}`:'')+(it.tags?' T':'')+(it.tulle?' U':'');n.badge.setText(it.faulty?'!':comps.trim()).setVisible(!!(it.faulty||comps.trim()))}
  renderFreezer(team,session,time){this.slotG.clear();const f=C.MAP.freezer;const slots=[{x:f.x+55,y:f.y+100},{x:f.x+157,y:f.y+100},{x:f.x+106,y:f.y+200}];slots.forEach((p,i)=>{const active=i<session.freezerCapacity||team.freezer.slots[i];this.slotG.fillStyle(active?0x18343d:0x222222,1);this.slotG.fillRoundedRect(p.x-38,p.y-32,76,64,8);this.slotG.lineStyle(2,active?0x78c7d3:0x555555,1);this.slotG.strokeRoundedRect(p.x-38,p.y-32,76,64,8);if(!active){this.slotG.lineStyle(3,0x777777,1);this.slotG.lineBetween(p.x-18,p.y-12,p.x+18,p.y+12);this.slotG.lineBetween(p.x+18,p.y-12,p.x-18,p.y+12)}});team.freezer.slots.forEach((id,i)=>{if(!id)return;const it=team.items[id];if(!it)return;const p=slots[i],r=C.RECIPES[it.recipeId];this.slotG.fillStyle(r.color,1);this.slotG.fillRoundedRect(p.x-25,p.y-17,50,34,6);this.slotG.lineStyle(2,0x231915,1);this.slotG.strokeRoundedRect(p.x-25,p.y-17,50,34,6)});let status='CARREGANDO';if(team.freezer.running){status=`RESFRIANDO · ${Math.max(0,Math.ceil((team.freezer.endAt-Date.now())/1000))}s`}else if(team.freezer.ready)status='PRONTO';this.freezerStatus.setText(status).setColor(team.freezer.ready?'#9df1bd':'#c8edf3')}
  renderProgress(team){this.progressG.clear();for(const s of C.MAP.assembly){const id=team.stationItems[s.id],it=id&&team.items[id];if(!it)continue;const progress=Math.min(1,(team.assemblyProgress[s.id]||0)/2.4);this.progressG.fillStyle(0x0d0a09,.8);this.progressG.fillRoundedRect(s.x+12,s.y+s.h-17,s.w-24,8,4);this.progressG.fillStyle(it.state==='assembled'?0x5acb89:0xe47a52,1);this.progressG.fillRoundedRect(s.x+12,s.y+s.h-17,(s.w-24)*progress,8,4)}}
}

function boot(){const role=qs('role');if(role==='facilitator')setupFacilitator();else if(role==='player')joinPage(qs('code')||'');else if(role==='observer'&&qs('code'))observerPage(qs('code').toUpperCase(),qs('team'));else home()}
boot();
})();
