(function(root){'use strict';
const C=root.ChocoV2;
const HOST_PREFIX='ccp-v2-';
const STORAGE_PREFIX='choco-v2-session-';
const LAST_HOST='choco-v2-host-last';

function safeSend(conn,data){try{if(conn&&conn.open)conn.send(data)}catch(e){console.warn('send failed',e)}}
function hostPeerId(code){return HOST_PREFIX+String(code).toLowerCase()}
function serializeSession(session){return JSON.stringify(session)}
function saveSession(session){try{localStorage.setItem(STORAGE_PREFIX+session.code,serializeSession(session));localStorage.setItem(LAST_HOST,session.code)}catch(e){console.warn('save failed',e)}}
function loadSession(code){try{const v=localStorage.getItem(STORAGE_PREFIX+String(code).toUpperCase());return v?JSON.parse(v):null}catch{return null}}
function lastSession(){try{return localStorage.getItem(LAST_HOST)||''}catch{return''}}

class FacilitatorHost{
  constructor(session,onUpdate){this.session=session;this.engine=new C.GameHostEngine(session);this.onUpdate=onUpdate||(()=>{});this.peer=null;this.clients=new Map();this.tickTimer=null;this.broadcastTimer=null;this.persistTimer=null;this.ready=false}
  start(){return new Promise((resolve,reject)=>{if(typeof Peer==='undefined')return reject(new Error('PeerJS não carregou.'));const id=hostPeerId(this.session.code);this.peer=new Peer(id,{debug:1});let settled=false;
      this.peer.on('open',()=>{this.ready=true;this.attach();this.beginLoops();saveSession(this.session);settled=true;resolve(this)});
      this.peer.on('connection',conn=>this.handleConnection(conn));
      this.peer.on('error',err=>{console.error(err);if(!settled)reject(err);this.onUpdate({type:'network-error',error:err})});
      this.peer.on('disconnected',()=>this.onUpdate({type:'network-disconnected'}));
    })}
  attach(){for(const p of Object.values(this.session.participants)){if(p.teamId&&!p.removed){p.connected=false;this.engine.addPlayer(p);const t=this.session.teams.find(t=>t.id===p.teamId);if(t?.players[p.id])t.players[p.id].connected=false}}}
  beginLoops(){this.tickTimer=setInterval(()=>{this.engine.tick();this.onUpdate({type:'tick'})},33);this.broadcastTimer=setInterval(()=>this.broadcast(),66);this.persistTimer=setInterval(()=>saveSession(this.session),1000)}
  stop(){clearInterval(this.tickTimer);clearInterval(this.broadcastTimer);clearInterval(this.persistTimer);for(const c of this.clients.values())try{c.conn.close()}catch{}this.clients.clear();try{this.peer?.destroy()}catch{}this.ready=false}
  handleConnection(conn){const meta={conn,role:'unknown',participantId:null,teamId:null,hello:false};this.clients.set(conn.peer,meta);conn.on('data',data=>this.handleData(meta,data));conn.on('close',()=>this.handleClose(meta));conn.on('error',()=>this.handleClose(meta))}
  handleData(client,data){if(!data||typeof data!=='object')return;if(!client.hello){if(data.type!=='hello')return;return this.handleHello(client,data)}
    if(client.role==='player'&&client.participantId){if(data.type==='input')this.engine.setInput(client.participantId,data.input||{});if(data.type==='action'&&['interact','dash','throw'].includes(data.action))this.engine.action(client.participantId,data.action)}
    if(client.role==='observer'&&data.type==='observe-team'){client.teamId=data.teamId}
  }
  handleHello(client,data){client.hello=true;if(data.role==='observer'){client.role='observer';client.teamId=data.teamId||this.session.teams[0]?.id;safeSend(client.conn,{type:'welcome-observer',session:C.publicSession(this.session)});return}
    if(data.role!=='player')return safeSend(client.conn,{type:'reject',reason:'Papel inválido.'});const token=String(data.token||''),name=String(data.name||'Participante').trim().slice(0,40)||'Participante';let p=Object.values(this.session.participants).find(x=>x.token===token&&!x.removed);
    if(!p){if(!this.session.entriesOpen){safeSend(client.conn,{type:'reject',reason:'Entradas fechadas pelo facilitador.'});return client.conn.close()}p={id:C.uid('player'),token:token||C.uid('token'),name,teamId:null,connected:true,peerId:client.conn.peer,joinedAt:C.now(),removed:false};this.session.participants[p.id]=p;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:`${name} entrou na sessão.`,type:'join'})}
    p.name=name;p.connected=true;p.peerId=client.conn.peer;client.role='player';client.participantId=p.id;client.teamId=p.teamId;if(p.teamId){this.engine.addPlayer(p);const t=this.session.teams.find(t=>t.id===p.teamId);if(t?.players[p.id])t.players[p.id].connected=true}safeSend(client.conn,{type:'welcome',participantId:p.id,token:p.token,session:C.publicSession(this.session)});this.onUpdate({type:'participant-join',participant:p});saveSession(this.session)
  }
  handleClose(client){this.clients.delete(client.conn.peer);if(client.participantId){const p=this.session.participants[client.participantId];if(p){p.connected=false;p.peerId=null;const team=this.session.teams.find(t=>t.id===p.teamId);if(team?.players[p.id])team.players[p.id].connected=false;this.onUpdate({type:'participant-leave',participant:p})}}}
  broadcast(){const pub=C.publicSession(this.session);for(const client of this.clients.values()){if(!client.hello||!client.conn.open)continue;if(client.role==='player'){const p=this.session.participants[client.participantId];if(!p||p.removed)continue;client.teamId=p.teamId;safeSend(client.conn,{type:'snapshot',session:pub,selfId:p.id,participant:{id:p.id,name:p.name,teamId:p.teamId,connected:p.connected},team:p.teamId?this.engine.teamSnapshot(p.teamId):null})}else if(client.role==='observer'){safeSend(client.conn,{type:'snapshot',session:pub,selfId:null,participant:null,team:client.teamId?this.engine.teamSnapshot(client.teamId):null,observer:true})}}
  }
  setEntries(open){this.session.entriesOpen=!!open;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:open?'Entradas abertas.':'Entradas fechadas.',type:'facilitator'});saveSession(this.session);this.onUpdate({type:'state'})}
  setPhase(phase){if(phase==='planning'){this.session.phase='planning';this.session.endsAt=C.now()+this.session.planningSeconds*1000;this.session.pausedRemaining=null;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Planejamento iniciado.',type:'phase'})}
    else if(phase==='production'){this.session.phase='production';this.session.endsAt=C.now()+this.session.productionSeconds*1000;this.session.pausedRemaining=null;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Produção iniciada.',type:'phase'})}
    else if(phase==='results'){this.session.phase='results';this.session.endsAt=null;this.session.pausedRemaining=null;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Dinâmica encerrada.',type:'phase'})}
    else{this.session.phase=phase;this.session.endsAt=null;this.session.pausedRemaining=null}saveSession(this.session);this.onUpdate({type:'state'})}
  pause(){if(this.session.pausedRemaining!=null||!this.session.endsAt)return;this.session.pausedRemaining=Math.max(0,(this.session.endsAt-C.now())/1000);this.session.endsAt=null;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Dinâmica pausada.',type:'phase'});this.onUpdate({type:'state'})}
  resume(){if(this.session.pausedRemaining==null)return;this.session.endsAt=C.now()+this.session.pausedRemaining*1000;this.session.pausedRemaining=null;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Dinâmica retomada.',type:'phase'});this.onUpdate({type:'state'})}
  addMinute(){if(this.session.endsAt)this.session.endsAt+=60000;else if(this.session.pausedRemaining!=null)this.session.pausedRemaining+=60;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'+1 minuto adicionado.',type:'phase'});this.onUpdate({type:'state'})}
  assignParticipant(playerId,teamId){const p=this.session.participants[playerId];if(!p||p.removed)return;if(teamId&&!this.session.teams.some(t=>t.id===teamId))return;if(p.teamId&&p.teamId!==teamId)this.engine.removePlayerFromWorld(p.id,p.teamId,true);p.teamId=teamId||null;if(p.teamId)this.engine.addPlayer(p);for(const c of this.clients.values())if(c.participantId===p.id)c.teamId=p.teamId;this.session.events.push({id:C.uid('evt'),t:C.now(),msg:`${p.name} → ${teamId?this.session.teams.find(t=>t.id===teamId).name:'Sem equipe'}.`,type:'assignment'});saveSession(this.session);this.onUpdate({type:'state'})}
  autoAssign(){const active=Object.values(this.session.participants).filter(p=>!p.removed);active.sort((a,b)=>a.joinedAt-b.joinedAt);active.forEach((p,i)=>this.assignParticipant(p.id,this.session.teams[i%this.session.teams.length].id));this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Participantes distribuídos automaticamente.',type:'assignment'});this.onUpdate({type:'state'})}
  removeParticipant(playerId){const p=this.session.participants[playerId];if(!p)return;if(p.teamId)this.engine.removePlayerFromWorld(p.id,p.teamId,true);p.removed=true;p.connected=false;for(const client of this.clients.values()){if(client.participantId===p.id){safeSend(client.conn,{type:'kicked',reason:'Você foi removido da sessão pelo facilitador.'});try{client.conn.close()}catch{}}}this.session.events.push({id:C.uid('evt'),t:C.now(),msg:`${p.name} removido da sessão.`,type:'assignment'});this.onUpdate({type:'state'})}
  sendMessage(text,teamId=null){text=String(text||'').trim().slice(0,180);if(!text)return;this.session.messages.push({id:C.uid('msg'),t:C.now(),text,teamId});if(this.session.messages.length>30)this.session.messages.shift();this.session.events.push({id:C.uid('evt'),t:C.now(),msg:`Mensagem enviada${teamId?' para '+this.session.teams.find(t=>t.id===teamId)?.name:' para todos'}: ${text}`,type:'message'});this.onUpdate({type:'state'})}
  applyMarket(){if(this.session.mode!=='pressure'||this.session.interventions.market)return;this.session.berriesPoints=3;this.session.interventions.market=true;this.sendMessage('ATUALIZAÇÃO DE MERCADO: Frutas Vermelhas agora valem 3 pontos.',null);this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Intervenção: Frutas Vermelhas 5 → 3 pontos.',type:'pressure'});this.onUpdate({type:'state'})}
  applyFreezer(){if(this.session.mode!=='pressure'||this.session.interventions.freezer)return;this.session.freezerCapacity=2;this.session.interventions.freezer=true;this.sendMessage('ALTERAÇÃO OPERACIONAL: capacidade do freezer reduzida de 3 para 2 nos próximos ciclos.',null);this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Intervenção: freezer 3 → 2.',type:'pressure'});this.onUpdate({type:'state'})}
  shareTalent(){if(this.session.mode!=='pressure'||this.session.interventions.talent)return;const teams=this.session.teams;const movers=teams.map(t=>Object.values(this.session.participants).filter(p=>p.teamId===t.id&&!p.removed&&p.connected).sort((a,b)=>a.joinedAt-b.joinedAt)[0]||null);if(movers.filter(Boolean).length<2)throw new Error('São necessários participantes conectados em pelo menos duas equipes.');const moves=[];movers.forEach((p,i)=>{if(!p)return;const target=teams[(i+1)%teams.length];moves.push([p,target.id])});for(const [p,target] of moves)this.engine.movePlayerTeam(p,target);this.session.interventions.talent=true;this.sendMessage('COMPARTILHAMENTO DE TALENTOS: houve uma realocação entre as fábricas. Adapte a estratégia.',null);this.session.events.push({id:C.uid('evt'),t:C.now(),msg:'Intervenção: compartilhamento de talentos aplicado.',type:'pressure'});this.onUpdate({type:'state'})}
  snapshotForFacilitator(){return{session:this.session,public:C.publicSession(this.session),teams:this.session.teams.map(t=>this.engine.teamSnapshot(t.id))}}
}

class ParticipantClient{
  constructor({code,name,token,role='player',teamId=null,onMessage,onState,onStatus}){this.code=String(code||'').toUpperCase();this.name=name||'Participante';this.token=token||C.uid('token');this.role=role;this.observeTeam=teamId;this.onMessage=onMessage||(()=>{});this.onState=onState||(()=>{});this.onStatus=onStatus||(()=>{});this.peer=null;this.conn=null;this.state=null;this.connected=false;this.reconnectTimer=null}
  start(){return new Promise((resolve,reject)=>{if(typeof Peer==='undefined')return reject(new Error('PeerJS não carregou.'));this.peer=new Peer(undefined,{debug:1});let opened=false;this.peer.on('open',()=>{opened=true;this.connect().then(resolve).catch(reject)});this.peer.on('error',err=>{console.error(err);this.onStatus({type:'error',error:err});if(!opened)reject(err)});this.peer.on('disconnected',()=>this.onStatus({type:'disconnected'}))})}
  connect(){return new Promise((resolve,reject)=>{const conn=this.peer.connect(hostPeerId(this.code),{reliable:true,serialization:'json'});this.conn=conn;let settled=false;const timeout=setTimeout(()=>{if(!settled){settled=true;reject(new Error('Não foi possível localizar a sessão. Verifique o código e mantenha a tela do facilitador aberta.'))}},9000);conn.on('open',()=>{safeSend(conn,{type:'hello',role:this.role,token:this.token,name:this.name,teamId:this.observeTeam});this.onStatus({type:'connected-signaling'})});conn.on('data',data=>{if(!data||typeof data!=='object')return;if(data.type==='welcome'){this.connected=true;this.token=data.token||this.token;this.participantId=data.participantId;localStorage.setItem('choco-v2-token-'+this.code,this.token);this.onMessage(data);if(!settled){settled=true;clearTimeout(timeout);resolve(this)}}else if(data.type==='welcome-observer'){this.connected=true;if(!settled){settled=true;clearTimeout(timeout);resolve(this)}}else if(data.type==='snapshot'){const prev=this.state;this.state=data;this.onState(data,prev)}else if(data.type==='reject'){this.onMessage(data);if(!settled){settled=true;clearTimeout(timeout);reject(new Error(data.reason||'Entrada recusada.'))}}else if(data.type==='kicked'){this.onMessage(data);this.stop()}});conn.on('close',()=>{this.connected=false;this.onStatus({type:'connection-closed'})});conn.on('error',err=>{this.onStatus({type:'error',error:err});if(!settled){settled=true;clearTimeout(timeout);reject(err)}})})}
  sendInput(input){safeSend(this.conn,{type:'input',input})}
  action(action){safeSend(this.conn,{type:'action',action})}
  observeTeam(teamId){this.observeTeam=teamId;safeSend(this.conn,{type:'observe-team',teamId})}
  stop(){clearTimeout(this.reconnectTimer);try{this.conn?.close()}catch{}try{this.peer?.destroy()}catch{}this.connected=false}
}

root.ChocoNet={FacilitatorHost,ParticipantClient,hostPeerId,saveSession,loadSession,lastSession};
})(window);
