(function(){'use strict';
const C=window.ChocoV2;
const hud={clock:document.getElementById('clock'),score:document.getElementById('score'),attempts:document.getElementById('attempts'),stock:document.getElementById('stock'),phase:document.getElementById('phase')};
const session=C.createSession({code:'DEMO01',mode:'pressure',teamCount:2,planningMinutes:2,productionMinutes:12});
session.phase='production';session.productionSeconds=720;session.endsAt=Date.now()+720000;session.berriesPoints=5;
const team=session.teams[0];
team.delivered={milk:6,dark:5,white:4,pistachio:1,berries:1,caramel:0};
team.attempts=12;team.inventory.baseBars=63;team.inventory.ribbons=44;team.inventory.tags=18;team.inventory.tulle=20;
const people=[
  {id:'you',token:'you',name:'Você',teamId:team.id,connected:true,joinedAt:1,removed:false},
  {id:'ana',token:'ana',name:'Ana',teamId:team.id,connected:true,joinedAt:2,removed:false},
  {id:'caio',token:'caio',name:'Caio',teamId:team.id,connected:true,joinedAt:3,removed:false}
];
people.forEach(p=>session.participants[p.id]=p);
const engine=new C.GameHostEngine(session);people.forEach(p=>engine.addPlayer(p));
team.players.you.x=615;team.players.you.y=370;team.players.ana.x=465;team.players.ana.y=385;team.players.caio.x=830;team.players.caio.y=390;
function item(id,recipeId,state,x,y,extra={}){const r=C.RECIPES[recipeId];return{id,recipeId,state,wrapper:extra.wrapper??(['raw','assembled'].includes(state)?null:r.wrapper),ribbons:extra.ribbons??(['raw','assembled'].includes(state)?0:r.ribbons),tags:extra.tags??(['raw','assembled'].includes(state)?0:r.tags),tulle:extra.tulle??(['raw','assembled'].includes(state)?0:r.tulle),faulty:false,x,y,holderId:null,stationId:extra.stationId||null,freezerSlot:extra.freezerSlot??null,ready:state==='ready',createdAt:Date.now()}}
const counter=item('counter-dark','dark','assembled',446,297,{stationId:'counter-1'});team.items[counter.id]=counter;team.stationItems['counter-1']=counter.id;
const floor=item('floor-pistachio','pistachio','finished',690,510);team.items[floor.id]=floor;
const f1=item('fz-milk','milk','finished',1067,330,{stationId:'freezer',freezerSlot:0});const f2=item('fz-white','white','finished',1169,330,{stationId:'freezer',freezerSlot:1});team.items[f1.id]=f1;team.items[f2.id]=f2;team.freezer.slots=[f1.id,f2.id,null];team.freezer.running=true;team.freezer.cooling=20;team.freezer.endAt=Date.now()+13000;team.freezer.batchStartedWith=2;

class PreviewScene extends Phaser.Scene{
  constructor(){super('Preview');this.players=new Map();this.items=new Map();this.lastInput=0;this.lastKey=''}
  create(){this.drawWorld();this.drawStations();this.drawGoal();this.keys=this.input.keyboard.addKeys({up:'W',down:'S',left:'A',right:'D',up2:'UP',down2:'DOWN',left2:'LEFT',right2:'RIGHT',interact:'E',interact2:'SPACE',dash:'SHIFT',throw:'Q'});this.input.keyboard.on('keydown-E',()=>engine.action('you','interact'));this.input.keyboard.on('keydown-SPACE',()=>engine.action('you','interact'));this.input.keyboard.on('keydown-SHIFT',()=>engine.action('you','dash'));this.input.keyboard.on('keydown-Q',()=>engine.action('you','throw'));this.notice=this.add.text(640,674,'WASD para mover · E para interagir · segure E na montagem · Q para lançar',{fontFamily:'Arial',fontSize:'12px',fontStyle:'bold',color:'#f7e9e1',backgroundColor:'#15100ee8',padding:{x:12,y:8}}).setOrigin(.5).setDepth(100)}
  drawWorld(){const g=this.add.graphics();g.fillStyle(0x211916,1);g.fillRect(0,0,1280,720);g.lineStyle(1,0x2c221e,.8);for(let x=22;x<1280;x+=48)g.lineBetween(x,22,x,698);for(let y=22;y<698;y+=48)g.lineBetween(22,y,1258,y);g.lineStyle(4,0x543a30,1);g.strokeRect(22,22,1236,676);this.add.text(36,30,'FÁBRICA A',{fontFamily:'Arial',fontSize:'18px',fontStyle:'bold',color:'#fff5ef'}).setDepth(20);this.add.text(36,53,'linha de produção compartilhada',{fontFamily:'Arial',fontSize:'10px',color:'#bdaaa0'}).setDepth(20)}
  station(s,fill,stroke,labelColor='#fff'){const g=this.add.graphics();g.fillStyle(0x000000,.28);g.fillRoundedRect(s.x+5,s.y+6,s.w,s.h,10);g.fillStyle(fill,1);g.fillRoundedRect(s.x,s.y,s.w,s.h,10);g.lineStyle(3,stroke,1);g.strokeRoundedRect(s.x,s.y,s.w,s.h,10);this.add.text(s.x+s.w/2,s.y+s.h/2,s.label,{fontFamily:'Arial',fontSize:'11px',fontStyle:'bold',color:labelColor,align:'center',wordWrap:{width:s.w-12}}).setOrigin(.5).setDepth(5)}
  drawStations(){for(const s of C.MAP.rawBins){const r=C.RECIPES[s.recipe];this.station(s,r.color,0x3c2922,r.id==='white'?'#2b1813':'#fff');this.add.text(s.x+s.w/2,s.y+9,`${r.base} barra${r.base>1?'s':''}`,{fontFamily:'Arial',fontSize:'9px',color:r.id==='white'?'#604b40':'#fff'}).setOrigin(.5,0).setDepth(6)}for(const s of C.MAP.wrappers){const r=Object.values(C.RECIPES).find(x=>x.wrapper===s.wrapper);this.station(s,r?.wrapperColor||0x82675a,0x3c2922,s.wrapper==='beige'?'#2b1813':'#fff')}C.MAP.assembly.forEach(s=>this.station(s,0x8f5138,0xca7652));C.MAP.counters.forEach(s=>this.station(s,0x65534a,0x90796d));C.MAP.finish.forEach(s=>this.station(s,s.resource==='ribbon'?0xb36048:s.resource==='tag'?0x5d7fa5:0x8e78aa,0x342620));this.station(C.MAP.freezer,0x315967,0x84ceda);this.station(C.MAP.freezerConsole,0x27414a,0x84ceda);this.station(C.MAP.dispatch,0x426a45,0x7fc084);this.slotG=this.add.graphics().setDepth(7);this.progressG=this.add.graphics().setDepth(8);this.freezerText=this.add.text(C.MAP.freezer.x+C.MAP.freezer.w/2,C.MAP.freezer.y+248,'',{fontFamily:'Arial',fontSize:'11px',fontStyle:'bold',color:'#c8edf3'}).setOrigin(.5).setDepth(10)}
  drawGoal(){const g=this.add.graphics().setDepth(80);g.fillStyle(0x0d0a09,.92);g.fillRoundedRect(970,30,270,178,12);g.lineStyle(2,0x51382f,1);g.strokeRoundedRect(970,30,270,178,12);this.add.text(990,45,'META DA FÁBRICA',{fontFamily:'Arial',fontSize:'11px',fontStyle:'bold',color:'#e58a68'}).setDepth(81);this.goal={};C.RECIPE_ORDER.forEach((k,i)=>this.goal[k]=this.add.text(990,70+i*21,'',{fontFamily:'Arial',fontSize:'12px',fontStyle:i<3?'bold':'normal',color:i<3?'#fff':'#d7c6bd'}).setDepth(81));this.scoreText=this.add.text(1155,45,'0 pts',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#fff'}).setDepth(81)}
  update(time){if(time-this.lastInput>50){this.lastInput=time;const input={up:this.keys.up.isDown||this.keys.up2.isDown,down:this.keys.down.isDown||this.keys.down2.isDown,left:this.keys.left.isDown||this.keys.left2.isDown,right:this.keys.right.isDown||this.keys.right2.isDown,interactHold:this.keys.interact.isDown||this.keys.interact2.isDown};const key=JSON.stringify(input);if(key!==this.lastKey||Object.values(input).some(Boolean)){this.lastKey=key;engine.setInput('you',input)}}this.renderPlayers();this.renderItems();this.renderFreezer();this.renderProgress();this.renderGoal()}
  renderPlayers(){const alive=new Set;for(const p of Object.values(team.players)){alive.add(p.id);let n=this.players.get(p.id);if(!n){n=this.makePlayer(p);this.players.set(p.id,n)}n.x=Phaser.Math.Linear(n.x,p.x,p.id==='you'?.42:.2);n.y=Phaser.Math.Linear(n.y,p.y,p.id==='you'?.42:.2)}for(const[id,n]of this.players)if(!alive.has(id)){n.destroy();this.players.delete(id)}}
  makePlayer(p){const c=this.add.container(p.x,p.y).setDepth(50);const sh=this.add.ellipse(0,14,42,18,0x000000,.28);const body=this.add.circle(0,0,18,team.color).setStrokeStyle(4,p.id==='you'?0xffffff:0x2d201b,1);const init=this.add.text(0,-1,p.name[0],{fontFamily:'Arial',fontSize:'14px',fontStyle:'bold',color:'#1d1411'}).setOrigin(.5);const name=this.add.text(0,27,p.name,{fontFamily:'Arial',fontSize:'10px',fontStyle:'bold',color:'#fff',backgroundColor:'#17110fcc',padding:{x:4,y:2}}).setOrigin(.5,0);const dot=this.add.circle(14,-14,4,0x54c98a);c.add([sh,body,init,name,dot]);return c}
  renderItems(){const alive=new Set;for(const it of Object.values(team.items)){if(it.freezerSlot!=null)continue;alive.add(it.id);let n=this.items.get(it.id);if(!n){n=this.makeItem(it);this.items.set(it.id,n)}n.x=Phaser.Math.Linear(n.x,it.x,.35);n.y=Phaser.Math.Linear(n.y,it.y,.35);this.updateItem(n,it)}for(const[id,n]of this.items)if(!alive.has(id)){n.destroy();this.items.delete(id)}}
  makeItem(it){const r=C.RECIPES[it.recipeId],c=this.add.container(it.x,it.y).setDepth(45);const sh=this.add.ellipse(3,7,35,15,0x000000,.3);const b=this.add.rectangle(0,0,34,22,r.color).setStrokeStyle(3,0x2f211c);const stripe=this.add.rectangle(0,0,34,5,r.wrapperColor).setVisible(false);const lab=this.add.text(0,0,r.short.slice(0,3),{fontFamily:'Arial',fontSize:'8px',fontStyle:'bold',color:r.id==='white'?'#2c1813':'#fff'}).setOrigin(.5);const badge=this.add.text(20,-15,'',{fontFamily:'Arial',fontSize:'8px',fontStyle:'bold',color:'#fff',backgroundColor:'#9d392d',padding:{x:3,y:1}}).setOrigin(.5);c.add([sh,b,stripe,lab,badge]);c.base=b;c.stripe=stripe;c.badge=badge;return c}
  updateItem(n,it){const r=C.RECIPES[it.recipeId];n.base.setFillStyle(r.color);n.stripe.setVisible(!!it.wrapper);if(it.wrapper){const wr=Object.values(C.RECIPES).find(x=>x.wrapper===it.wrapper);n.stripe.setFillStyle(wr?.wrapperColor||0xffffff)}const comps=(it.ribbons?`F${it.ribbons}`:'')+(it.tags?' T':'')+(it.tulle?' U':'');n.badge.setText(it.faulty?'!':comps.trim()).setVisible(!!(it.faulty||comps.trim()))}
  renderFreezer(){this.slotG.clear();const f=C.MAP.freezer,slots=[{x:f.x+55,y:f.y+100},{x:f.x+157,y:f.y+100},{x:f.x+106,y:f.y+200}];slots.forEach((p,i)=>{const active=i<session.freezerCapacity||team.freezer.slots[i];this.slotG.fillStyle(active?0x18343d:0x222222,1);this.slotG.fillRoundedRect(p.x-38,p.y-32,76,64,8);this.slotG.lineStyle(2,active?0x78c7d3:0x555555,1);this.slotG.strokeRoundedRect(p.x-38,p.y-32,76,64,8)});team.freezer.slots.forEach((id,i)=>{if(!id)return;const it=team.items[id];if(!it)return;const p=slots[i],r=C.RECIPES[it.recipeId];this.slotG.fillStyle(r.color,1);this.slotG.fillRoundedRect(p.x-25,p.y-17,50,34,6);this.slotG.lineStyle(2,0x231915,1);this.slotG.strokeRoundedRect(p.x-25,p.y-17,50,34,6)});let status='CARREGANDO';if(team.freezer.running)status=`RESFRIANDO · ${Math.max(0,Math.ceil((team.freezer.endAt-Date.now())/1000))}s`;else if(team.freezer.ready)status='PRONTO';this.freezerText.setText(status).setColor(team.freezer.ready?'#9df1bd':'#c8edf3')}
  renderProgress(){this.progressG.clear();for(const s of C.MAP.assembly){const id=team.stationItems[s.id],it=id&&team.items[id];if(!it)continue;const p=Math.min(1,(team.assemblyProgress[s.id]||0)/2.4);this.progressG.fillStyle(0x0d0a09,.8);this.progressG.fillRoundedRect(s.x+12,s.y+s.h-17,s.w-24,8,4);this.progressG.fillStyle(it.state==='assembled'?0x5acb89:0xe47a52,1);this.progressG.fillRoundedRect(s.x+12,s.y+s.h-17,(s.w-24)*p,8,4)}}
  renderGoal(){const sc=C.scoreTeam(team,session);this.scoreText.setText(`${sc.total} pts`);C.RECIPE_ORDER.forEach((k,i)=>{const r=C.RECIPES[k],n=team.delivered[k]||0;this.goal[k].setText(i<3?`${r.short.padEnd(9,' ')} ${n}/10`:`${r.short.padEnd(9,' ')} ${n} · ${k==='berries'?session.berriesPoints:r.points} pts`);this.goal[k].setColor(i<3&&n>=10?'#80d7a4':i<3?'#fff':'#d7c6bd')})}
}

const game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#1b1411',width:1280,height:720,scene:[PreviewScene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false}});
let angle=0;
setInterval(()=>{engine.tick();angle+=.03;const a=team.players.ana,c=team.players.caio;if(a){a.x=465+Math.sin(angle)*36;a.y=385+Math.cos(angle*.75)*24;a.dir=Math.cos(angle)>0?'right':'left'}if(c){c.x=830+Math.cos(angle*.65)*48;c.y=390+Math.sin(angle)*30;c.dir=Math.sin(angle)>0?'down':'up'}hud.clock.textContent=fmt(C.phaseRemaining(session));const sc=C.scoreTeam(team,session);hud.score.textContent=`${sc.total} pts`;hud.attempts.textContent=`${team.attempts}/50 tentativas`;hud.stock.textContent=`Barras ${team.inventory.baseBars} · Fitas ${team.inventory.ribbons}`},50);
function fmt(sec){sec=Math.max(0,Math.ceil(Number(sec)||0));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
})();
