(()=>{'use strict';
const R={
 milk:{n:'Ao Leite',p:1,t:20,b:1,w:'Marrom claro',r:1,tag:0,tulle:0,c:0xb97a57},
 dark:{n:'Amargo',p:1,t:20,b:1,w:'Marrom escuro',r:1,tag:0,tulle:0,c:0x5f3b31},
 white:{n:'Branco',p:1,t:20,b:1,w:'Bege',r:1,tag:0,tulle:0,c:0xead8b6},
 pistachio:{n:'Pistache',p:3,t:45,b:2,w:'Verde',r:1,tag:1,tulle:0,c:0x84a96b},
 berries:{n:'Frutas Vermelhas',p:5,t:50,b:2,w:'Vermelho',r:1,tag:1,tulle:0,c:0xb95156},
 caramel:{n:'Caramelo',p:7,t:60,b:2,w:'Amarelo',r:2,tag:1,tulle:1,c:0xd7a24a}
};
const app=document.getElementById('app'),toastEl=document.getElementById('toast');
let code='',pid='',game=null,sceneRef=null,selected='milk';
const qs=new URLSearchParams(location.search);
const key=c=>'choco-v4-'+c;
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const load=c=>{try{return JSON.parse(localStorage.getItem(key(c)))}catch{return null}};
const save=s=>{localStorage.setItem(key(s.code),JSON.stringify(s));return s};
function toast(m,bad=false){toastEl.textContent=m;toastEl.className='toast'+(bad?' bad':'');toastEl.hidden=false;setTimeout(()=>toastEl.hidden=true,2100)}
function rem(s){if(s.paused!=null)return s.paused;if(!s.endsAt)return 0;return Math.max(0,Math.ceil((s.endsAt-Date.now())/1000))}
function fmt(v){v=Math.max(0,v|0);return String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0')}
function phase(s){return({lobby:'Lobby',planning:'Planejamento',production:'Produção',results:'Encerrado'})[s.phase]||s.phase}
function findPlayer(s,id){for(const t of s.teams||[]){const p=(t.players||[]).find(x=>x.id===id);if(p)return{team:t,player:p}}return null}
function settle(s){let changed=false;(s.teams||[]).forEach(t=>{if(t.freezer&&t.freezer.items&&t.freezer.items.length&&t.freezer.end<=Date.now()){t.done.push(...t.freezer.items.map(x=>({id:x.id,f:x.f})));t.freezer=null;changed=true}});if(changed)save(s);return s}
function score(t,s){const c={milk:0,dark:0,white:0,pistachio:0,berries:0,caramel:0};(t.done||[]).forEach(x=>{if(c[x.f]!=null)c[x.f]++});const ok=c.milk>=10&&c.dark>=10&&c.white>=10;return{c,ok,total:c.milk+c.dark+c.white+(ok?c.pistachio*3+c.berries*s.berries+c.caramel*7:0)}}
function mutate(fn){let s=load(code);if(!s)return toast('Sessão não encontrada.',true);try{s=fn(s)||s;save(s);if(sceneRef)rebuild(sceneRef);return s}catch(e){toast(e.message||String(e),true)}}
function mkDemo(){const team=(i)=>({id:'demo-t'+i,name:'Fábrica '+String.fromCharCode(65+i),players:[],inv:{base:70,ribbons:50,tags:20,tulle:20,wrap:{'Marrom claro':30,'Marrom escuro':30,'Bege':30,'Verde':20,'Vermelho':20,'Amarelo':20}},prepared:[],freezer:null,done:[],pen:[]});const s={code:'DEMO01',mode:'pressure',phase:'production',entries:true,plan:600,prod:900,endsAt:Date.now()+540000,paused:null,cap:3,berries:5,inter:{talent:0,market:0,cap:0},teams:[team(0),team(1)],events:[]};s.teams[0].players=[{id:'demo-player',name:'Gabriel'}];s.teams[0].done=[...Array(6)].map(()=>({id:uid(),f:'milk'})).concat([...Array(5)].map(()=>({id:uid(),f:'dark'})),[...Array(4)].map(()=>({id:uid(),f:'white'})));s.teams[0].prepared=[{id:uid(),f:'milk'},{id:uid(),f:'white'}];save(s);code='DEMO01';pid='demo-player'}
function joinScreen(){if(game){game.destroy(true);game=null;sceneRef=null}const s=code.length===6?load(code):null;app.innerHTML=`<main class="shell"><section class="join"><span class="eyebrow">PARTICIPANTE · PHASER 4</span><h1>Entrar na fábrica</h1><p class="muted">Use o código criado pelo facilitador. Nesta etapa de protótipo, a sessão precisa existir no mesmo navegador.</p><label>Código</label><input id="c" maxlength="6" value="${code}" placeholder="ABC123">${s?`<label>Nome</label><input id="name" placeholder="Seu nome"><label>Equipe</label><select id="team">${s.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select><button class="btn primary" id="enter" style="width:100%;margin-top:18px" ${s.entries?'':'disabled'}>${s.entries?'Entrar na fábrica':'Entradas fechadas'}</button>`:''}<div class="row" style="margin-top:14px"><button class="btn" id="demo">Abrir demo Phaser</button><a class="btn" href="../" style="text-decoration:none">Voltar</a></div></section></main>`;c.oninput=e=>{code=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);e.target.value=code;if(code.length===6)setTimeout(joinScreen,0)};demo.onclick=()=>{mkDemo();launch()};if(s&&document.getElementById('enter'))enter.onclick=()=>{const n=name.value.trim();if(!n)return toast('Informe seu nome.',true);const t=s.teams.find(x=>x.id===team.value);const p={id:uid(),name:n};t.players.push(p);save(s);pid=p.id;sessionStorage.setItem('choco-p-'+s.code,pid);launch()}}
function launch(){if(game){game.destroy(true);game=null}let s=settle(load(code)),id=pid||sessionStorage.getItem('choco-p-'+code),fp=s&&findPlayer(s,id);if(!s||!fp)return joinScreen();pid=id;app.innerHTML=`<main class="shell"><section class="game-card"><header class="topbar"><div><small>${fp.team.name} · ${fp.player.name}</small><b>Fábrica compartilhada</b></div><div class="pills"><span class="pill" id="phase">${phase(s)}</span><span class="pill" id="clock">${fmt(rem(s))}</span><span class="pill">Phaser 4.2.1</span></div></header><div id="game" class="game-host"></div><div class="hint">Monte uma barra, depois arraste-a para o freezer. Só entram no mesmo ciclo barras com o mesmo tempo de resfriamento. Clicar numa barra antes do fim invalida o produto.</div></section></main>`;game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1180,height:690,backgroundColor:'#191513',render:{antialias:true},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{create(){sceneRef=this;this.ui={dyn:[],sig:''};drawBase(this);rebuild(this)},update(){tick(this)}}})}
function rr(sc,x,y,w,h,r,fill,stroke=0,sw=0,a=1){const g=sc.add.graphics();g.fillStyle(fill,a);g.fillRoundedRect(x,y,w,h,r);if(sw){g.lineStyle(sw,stroke,1);g.strokeRoundedRect(x,y,w,h,r)}return g}
function txt(sc,x,y,t,size=14,color='#fff8f3',bold=false){return sc.add.text(x,y,t,{fontFamily:'Inter, Arial, sans-serif',fontSize:size+'px',fontStyle:bold?'bold':'normal',color})}
function track(sc,o){sc.ui.dyn.push(o);return o}
function clear(sc){(sc.ui.dyn||[]).forEach(o=>{try{o.destroy()}catch{}});sc.ui.dyn=[]}
function drawBase(sc){rr(sc,18,18,1144,82,18,0x2c211d,0x533b32,1);txt(sc,38,35,'META DA FÁBRICA',11,'#d38a67',true);txt(sc,38,58,'Complete 10 + 10 + 10 antes de buscar os premium',15,'#fff8f3',true);rr(sc,18,118,220,430,18,0x30241f,0x543c32,1);txt(sc,38,140,'ESTOQUE',12,'#d38a67',true);txt(sc,38,164,'Recursos compartilhados',13,'#d4c1b8');rr(sc,258,118,510,430,18,0x2a211d,0x543c32,1);txt(sc,278,140,'BANCADA',12,'#d38a67',true);txt(sc,278,164,'Produção da equipe',13,'#d4c1b8');rr(sc,788,118,374,430,18,0x202a2c,0x3f6167,1);txt(sc,808,140,'FREEZER',12,'#8ccbd5',true);txt(sc,808,164,'Gargalo da fábrica',13,'#cce6ea');rr(sc,18,566,1144,106,18,0x251d19,0x4c372f,1);txt(sc,38,584,'RECEITAS',11,'#d38a67',true)}
function signature(s,t){return JSON.stringify({phase:s.phase,paused:s.paused,endsAt:s.endsAt,cap:s.cap,berries:s.berries,team:t})}
function tick(sc){let s=settle(load(code));if(!s)return;const fp=findPlayer(s,pid);if(!fp)return;const sg=signature(s,fp.team);if(sg!==sc.ui.sig)rebuild(sc);const c=document.getElementById('clock');if(c)c.textContent=fmt(rem(s));const p=document.getElementById('phase');if(p)p.textContent=s.paused!=null?'Pausado':phase(s)}
function button(sc,x,y,w,h,label,enabled,onClick){const bg=track(sc,rr(sc,x,y,w,h,10,enabled?0x923722:0x55433b,enabled?0xb85a3b:0x6b574f,1));track(sc,txt(sc,x+w/2,y+h/2,label,14,'#fff',true).setOrigin(.5));const z=track(sc,sc.add.zone(x,y,w,h).setOrigin(0).setInteractive({useHandCursor:enabled}));if(enabled)z.on('pointerdown',onClick);return bg}
function rebuild(sc){clear(sc);let s=settle(load(code)),fp=findPlayer(s,pid);if(!fp)return;const t=fp.team,st=score(t,s),active=s.phase==='production'&&s.paused==null&&rem(s)>0;sc.ui.sig=signature(s,t);
 let x=470;[['Ao Leite','milk'],['Amargo','dark'],['Branco','white']].forEach(([n,k])=>{const v=st.c[k],ok=v>=10;track(sc,rr(sc,x,37,150,44,12,ok?0x254a39:0x3a2b25,ok?0x4d8b6e:0x5e453b,1));track(sc,txt(sc,x+12,47,n,10,'#d8c7bf'));track(sc,txt(sc,x+110,47,`${v}/10`,16,ok?'#9ce0b6':'#fff',true));x+=162});track(sc,txt(sc,980,44,`${st.total} pts`,24,'#fff',true));
 let iy=205;[['Barras',t.inv.base],['Fitas',t.inv.ribbons],['Tags',t.inv.tags],['Tule',t.inv.tulle]].forEach(([n,v])=>{track(sc,rr(sc,38,iy,180,52,11,0x3a2c26,0x5b4338,1));track(sc,txt(sc,50,iy+10,n,11,'#cebcb3'));track(sc,txt(sc,186,iy+8,String(v),23,'#fff',true).setOrigin(1,0));iy+=62});track(sc,txt(sc,38,462,'Embalagens',11,'#d38a67',true));[['Leite','Marrom claro'],['Amargo','Marrom escuro'],['Branco','Bege']].forEach((a,i)=>{track(sc,txt(sc,38,486+i*19,a[0],10,'#cdbab1'));track(sc,txt(sc,204,486+i*19,String(t.inv.wrap[a[1]]),11,'#fff',true).setOrigin(1,0))});
 const r=R[selected];track(sc,rr(sc,278,196,470,88,14,0x352923,0x5f473c,1));track(sc,txt(sc,298,211,'Receita selecionada',10,'#d38a67',true));track(sc,txt(sc,298,232,r.n,24,'#fff',true));track(sc,txt(sc,298,262,`${selected==='berries'?s.berries:r.p} pts · ${r.t}s no freezer`,12,'#ccb9b0'));button(sc,278,302,470,52,active?'MONTAR BARRA':'AGUARDE A PRODUÇÃO',active,()=>prepare(t.id,selected));track(sc,txt(sc,278,376,'Barras prontas — arraste para o freezer',11,'#d38a67',true));if(!t.prepared.length)track(sc,txt(sc,278,410,'Nenhuma barra pronta.',14,'#9d8b83'));else t.prepared.slice(0,6).forEach((it,i)=>preparedToken(sc,it,278+(i%3)*152,410+Math.floor(i/3)*68,t.id,active));
 const cap=s.cap,f=t.freezer;track(sc,txt(sc,808,196,`Capacidade atual: ${cap}`,13,'#d5edf0',true));for(let i=0;i<3;i++){const locked=i>=cap;track(sc,rr(sc,808+i*112,232,96,150,14,locked?0x293133:0x29383b,locked?0x465255:0x52777e,2));track(sc,txt(sc,856+i*112,247,locked?'BLOQ.':`SLOT ${i+1}`,10,locked?'#7f8d90':'#a3d7df',true).setOrigin(.5,0));const it=f&&f.items?f.items[i]:null;if(it)freezerItem(sc,it,821+i*112,280,t.id,active,f.end)}if(f&&f.items&&f.items.length){const left=Math.max(0,Math.ceil((f.end-Date.now())/1000));track(sc,txt(sc,808,405,'Ciclo em andamento',11,'#8ccbd5',true));track(sc,txt(sc,808,428,left+'s restantes',30,'#fff',true));track(sc,txt(sc,808,470,`${R[f.items[0].f].t}s · ${f.items.length}/${cap} barras`,12,'#c4dde1'))}else{track(sc,txt(sc,808,417,'FREEZER LIVRE',27,'#b8e0e6',true));track(sc,txt(sc,808,454,'Arraste uma barra pronta para cá.',12,'#a4c6cb'))}if(t.pen.length)track(sc,txt(sc,808,507,'⚠ '+t.pen[t.pen.length-1],11,'#f3aaa0'));
 Object.entries(R).forEach(([k,v],i)=>{const rx=38+i*184,sel=k===selected;track(sc,rr(sc,rx,610,168,42,10,sel?0x923722:0x3a2b25,sel?0xbd5a3b:0x5b433a,1));track(sc,txt(sc,rx+12,620,v.n,11,sel?'#fff':'#e0d2cb',true));const z=track(sc,sc.add.zone(rx,610,168,42).setOrigin(0).setInteractive({useHandCursor:true}));z.on('pointerdown',()=>{selected=k;rebuild(sc)})});
 if(s.paused!=null){track(sc,rr(sc,340,285,500,86,16,0x181210,0x6c4d42,2,.97));track(sc,txt(sc,590,306,'DINÂMICA PAUSADA',22,'#fff',true).setOrigin(.5,0));track(sc,txt(sc,590,340,'Aguarde o facilitador retomar.',12,'#d9c8c1').setOrigin(.5,0))}}
function prepare(teamId,flavor){mutate(s=>{const t=s.teams.find(x=>x.id===teamId),r=R[flavor];if(t.inv.base<r.b||t.inv.ribbons<r.r||t.inv.tags<r.tag||t.inv.tulle<r.tulle||t.inv.wrap[r.w]<1)throw Error('Recursos insuficientes.');t.inv.base-=r.b;t.inv.ribbons-=r.r;t.inv.tags-=r.tag;t.inv.tulle-=r.tulle;t.inv.wrap[r.w]--;t.prepared.push({id:uid(),f:flavor});return s})}
function preparedToken(sc,it,x,y,teamId,active){const r=R[it.f],c=track(sc,sc.add.container(x,y));const bg=sc.add.rectangle(0,0,138,54,r.c).setOrigin(0);bg.setStrokeStyle(2,0xffffff,.3);const a=sc.add.text(10,8,r.n,{fontFamily:'Inter, Arial',fontSize:'11px',fontStyle:'bold',color:'#fff'}),b=sc.add.text(10,30,r.t+'s',{fontFamily:'Inter, Arial',fontSize:'10px',color:'#f0e6e1'});c.add([bg,a,b]);c.setSize(138,54);if(active){c.setInteractive({useHandCursor:true});sc.input.setDraggable(c);c.on('drag',(p,dx,dy)=>{c.x=dx;c.y=dy});c.on('dragend',()=>{if(c.x>770&&c.x<1160&&c.y>180&&c.y<520)drop(it.id,teamId);else rebuild(sc)})}}
function drop(itemId,teamId){mutate(s=>{const t=s.teams.find(x=>x.id===teamId),idx=t.prepared.findIndex(x=>x.id===itemId);if(idx<0)return s;const it=t.prepared[idx],r=R[it.f];if(t.freezer&&t.freezer.items.length>=s.cap)throw Error('Freezer cheio.');if(t.freezer&&t.freezer.items.length&&R[t.freezer.items[0].f].t!==r.t)throw Error('Tempo incompatível com o ciclo atual.');t.prepared.splice(idx,1);if(!t.freezer)t.freezer={items:[it],end:Date.now()+r.t*1000};else t.freezer.items.push(it);return s})}
function freezerItem(sc,it,x,y,teamId,active,end){const r=R[it.f],bg=track(sc,sc.add.rectangle(x,y,70,70,r.c).setOrigin(0));bg.setStrokeStyle(2,0xe7f3f5,.45);track(sc,txt(sc,x+35,y+18,r.n.split(' ')[0],10,'#fff',true).setOrigin(.5,0));track(sc,txt(sc,x+35,y+40,Math.max(0,Math.ceil((end-Date.now())/1000))+'s',15,'#fff',true).setOrigin(.5,0));if(active){bg.setInteractive({useHandCursor:true});bg.on('pointerdown',()=>pullEarly(it.id,teamId))}}
function pullEarly(itemId,teamId){mutate(s=>{const t=s.teams.find(x=>x.id===teamId);if(!t.freezer)return s;const idx=t.freezer.items.findIndex(x=>x.id===itemId);if(idx<0)return s;const [it]=t.freezer.items.splice(idx,1);t.pen.push('Retirada antecipada: '+R[it.f].n+' invalidado.');if(!t.freezer.items.length)t.freezer=null;return s})}
window.addEventListener('storage',e=>{if(code&&e.key===key(code)&&sceneRef)rebuild(sceneRef)});
if(qs.get('demo')==='1'){mkDemo();launch()}else{code=(qs.get('join')||'').toUpperCase();pid=sessionStorage.getItem('choco-p-'+code)||'';if(code&&pid&&load(code)&&findPlayer(load(code),pid))launch();else joinScreen()}
})();